use_frameworks!

platform :ios, '8.0'

target 'BLCollectionViewTagLayout_Example' do
  pod 'BLCollectionViewTagLayout', :path => '../'

  target 'BLCollectionViewTagLayout_Tests' do
    inherit! :search_paths

    
  end
end
